[github_app]
pr_commands = [
    "/describe",
    "/review",
    "/improve",
]

[pr_reviewer] # /review #
# enable/disable features
require_estimate_effort_to_review=false
enable_review_labels_effort=false